# Generated by Django 3.1.7 on 2021-04-01 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='medic',
            field=models.IntegerField(choices=[(0, 'Sim'), (1, 'Nao')], default=1),
        ),
    ]
