# Generated by Django 3.1.7 on 2021-04-05 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_medic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='medic',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=1),
        ),
    ]
