# Generated by Django 3.1.7 on 2021-04-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210405_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default=' ', max_length=255, unique=True),
        ),
    ]
