# Generated by Django 3.1.7 on 2021-04-09 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_medic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_specialist',
            field=models.BooleanField(default=False),
        ),
    ]
