# Generated by Django 3.2 on 2021-04-20 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('als', '0005_alter_al_activated'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('id_al', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='als.al')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='trainining/%Y/%m/%d')),
                ('label', models.BooleanField(default=True)),
                ('id_dataset', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='training.trainingdataset')),
            ],
        ),
    ]
