# Generated by Django 3.1.7 on 2021-03-26 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='exam',
            fields=[
                ('IDExam', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ExamDate', models.DateField(max_length=100)),
                ('ExamType', models.CharField(max_length=100)),
                ('ExamNotes', models.TextField(max_length=1000)),
                ('ExamResult', models.TextField(max_length=1000)),
            ],
            options={
                'ordering': ['IDExam'],
            },
        ),
    ]
