# Generated by Django 3.2 on 2021-04-20 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('n_instances', models.IntegerField(default=10)),
                ('accuracy_goal', models.FloatField(default=85)),
            ],
        ),
    ]
