# Generated by Django 3.2 on 2021-04-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('als', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='al',
            name='query_technic',
            field=models.CharField(choices=[('RandomSampling', 'RandomSampling'), ('UncertaintySampling', 'UncertaintySampling'), ('ClusterBasedSampling', 'ClusterBasedSampling'), ('OutlierSampling', 'OutlierSampling'), ('RepresentativeSampling', 'RepresentativeSampling'), ('UncertaintyWithClusteringSampling', 'UncertaintyWithClusteringSampling'), ('UncertaintyWithModelOutliersSampling', 'UncertaintyWithModelOutliersSampling'), ('RepresentativeWithClusteringSampling', 'RepresentativeWithClusteringSampling'), ('HighestEntropyClusteringSampling', 'HighestEntropyClusteringSampling'), ('UncertaintyWithRepresentativeSampling', 'UncertaintyWithRepresentativeSampling'), ('HighestEntropyUncertaintySampling', 'HighestEntropyUncertaintySampling'), ('OutliersWithRepresentativeSampling', 'OutliersWithRepresentativeSampling')], default='RandomSampling', max_length=50),
        ),
    ]
