# Generated by Django 3.2 on 2021-04-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('als', '0002_al_query_technic'),
    ]

    operations = [
        migrations.AddField(
            model_name='al',
            name='model',
            field=models.CharField(choices=[('cnn', 'cnn'), ('vgg16', 'vgg16'), ('vgg19', 'vgg19'), ('resnet50', 'resnet50'), ('resnet50v2', 'resnet50v2'), ('xception', 'xception'), ('inceptionv3', 'inceptionv3')], default='cnn', max_length=50),
        ),
    ]
