# Generated by Django 3.2 on 2021-04-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('als', '0003_al_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='al',
            name='activated',
            field=models.BooleanField(default=False),
        ),
    ]
