# Generated by Django 3.2 on 2021-04-25 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('als', '0006_auto_20210425_1707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='al',
            old_name='testing_activated',
            new_name='predicting_activated',
        ),
    ]
