# Generated by Django 3.2 on 2021-04-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('als', '0007_rename_testing_activated_al_predicting_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='al',
            name='model_weights',
            field=models.FileField(null=True, upload_to='models'),
        ),
    ]
