# Generated by Django 3.2 on 2021-04-26 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('als', '0011_alter_al_model_weights'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='al',
            name='model_weights',
        ),
    ]
