# Generated by Django 3.2 on 2021-04-26 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('als', '0012_remove_al_model_weights'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iteration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracy', models.FloatField(default=0)),
                ('id_al', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='als.al')),
            ],
        ),
    ]
