# Generated by Django 3.1.7 on 2021-04-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacients', '0002_auto_20210326_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacient',
            name='Gender',
            field=models.IntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Prefer not to say')]),
        ),
    ]
