# Generated by Django 3.1.7 on 2021-04-05 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacients', '0003_auto_20210401_1624'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pacient',
            options={'ordering': ['id_pacient']},
        ),
        migrations.RenameField(
            model_name='pacient',
            old_name='BirthDate',
            new_name='birth_date',
        ),
        migrations.RenameField(
            model_name='pacient',
            old_name='FirstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='pacient',
            old_name='IDPacient',
            new_name='id_pacient',
        ),
        migrations.RenameField(
            model_name='pacient',
            old_name='LastName',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='pacient',
            old_name='Remarks',
            new_name='remarks',
        ),
        migrations.RenameField(
            model_name='pacient',
            old_name='IDPacientAnonym',
            new_name='total_exams',
        ),
        migrations.RemoveField(
            model_name='pacient',
            name='TotalExams',
        ),
    ]
