# Generated by Django 3.1.7 on 2021-04-05 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacients', '0004_auto_20210405_0132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pacient',
            old_name='Gender',
            new_name='gender',
        ),
    ]
