# Generated by Django 3.1.7 on 2021-04-09 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacients', '0005_auto_20210405_0343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacient',
            name='gender',
        ),
    ]
