# Generated by Django 3.2 on 2021-04-17 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacients', '0006_remove_pacient_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacient',
            name='total_exams',
            field=models.IntegerField(default=0),
        ),
    ]
