# Generated by Django 3.2 on 2021-04-26 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0003_auto_20210418_0055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endoscopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('id_exam', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='exams.exam')),
            ],
        ),
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='endoscopies/%Y/%m/%d')),
                ('id_endoscopy', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='endoscopies.endoscopy')),
            ],
        ),
    ]
